### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Thijxx** [ArangoDB-Community/aql-intellij-plugin#8]
I installed the plugin. Now what?
Nothing in Drivers, nothing Data Sources. Not under Data Source from URL. Nothing in README. No info on plugin page. No button in plug-ins overview in Datagrip. 

Really clue-less how to use it.

**Comment by machak** [comment]
you should have ArangoDB console and sources window, e..g. as displayed at:

https://raw.githubusercontent.com/ArangoDB-Community/aql-intellij-plugin/master/img/editor.png 

Check Intellij log files to see if plugin might be disabled due to incompatibility errors. 
Also, File > New >  menu should contain option to create AQL file.

**Comment by Thijxx** [comment]
ah yes I found the window using the Search function, thank you! I was expecting it under Data Sources..

**Comment by machak** [comment]
Data sources is "closed source" unfortunately (and Ultimate version only I believe)
